# Generated by Django 5.2.7 on 2025-10-02 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSellingPreconfiguredProduct',
            fields=[
                ('preconfigured_product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('times_ordered', models.IntegerField()),
            ],
            options={
                'db_table': 'bestsellingpreconfiguredproduct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopPreconfiguredProductsPerCategory',
            fields=[
                ('preconfigured_product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField()),
                ('preconfigured_name', models.CharField(max_length=255)),
                ('times_ordered', models.IntegerField()),
            ],
            options={
                'db_table': 'toppreconfiguredproductspercategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreConfiguredProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='preconfigured_products/')),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'db_table': 'preconfiguredproduct',
            },
        ),
        migrations.CreateModel(
            name='PreConfiguredProductParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.partoption')),
                ('preconfigured_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='preconfigured_products.preconfiguredproduct')),
            ],
            options={
                'db_table': 'preconfiguredproductparts',
            },
        ),
    ]
