# Generated by Django 5.2.7 on 2025-10-02 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('step', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'db_table': 'part',
            },
        ),
        migrations.CreateModel(
            name='PartOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='part_options/')),
                ('description', models.TextField(blank=True, null=True)),
                ('minimum_payment_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum upfront payment required (0.00 to 1.00). Example: 0.70 means 70% required upfront', max_digits=3)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.part')),
            ],
            options={
                'db_table': 'partoption',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('part_option', models.ForeignKey(db_column='part_option_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.partoption')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
