# Generated by Django 5.2.7 on 2025-10-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partoption',
            name='minimum_payment_percentage',
            field=models.DecimalField(
                decimal_places=2,
                default=0.00,
                help_text='Minimum upfront payment required (0.00 to 1.00). Example: 0.70 means 70% required upfront',
                max_digits=3
            ),
        ),
    ]
