# Generated by Django 5.2.7 on 2025-10-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_boda_quantity',
            field=models.IntegerField(default=1, help_text='Maximum quantity deliverable by boda boda (0 = never use boda)'),
        ),
        migrations.AddField(
            model_name='category',
            name='requires_extra_care',
            field=models.BooleanField(default=False, help_text='Fragile or valuable items requiring extra care'),
        ),
        migrations.AddField(
            model_name='category',
            name='requires_helper',
            field=models.BooleanField(default=False, help_text='Requires delivery assistance or assembly help'),
        ),
        migrations.AddField(
            model_name='category',
            name='shipping_notes',
            field=models.TextField(blank=True, help_text='Special shipping/handling instructions'),
        ),
        migrations.AddField(
            model_name='category',
            name='stackable',
            field=models.BooleanField(default=False, help_text='Can items be stacked efficiently for delivery?'),
        ),
        migrations.AddField(
            model_name='category',
            name='unit_height_cm',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Height per single item in centimeters', max_digits=6),
        ),
        migrations.AddField(
            model_name='category',
            name='unit_length_cm',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Length per single item in centimeters', max_digits=6),
        ),
        migrations.AddField(
            model_name='category',
            name='unit_weight_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Weight per single item in kilograms', max_digits=6),
        ),
        migrations.AddField(
            model_name='category',
            name='unit_width_cm',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Width per single item in centimeters', max_digits=6),
        ),
    ]
