# Generated by Django 5.2.7 on 2025-10-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preferred_currency',
            field=models.CharField(default='UGX', help_text="Customer's preferred currency for viewing prices (ISO 4217 code)", max_length=3),
        ),
    ]
