# Generated by Django 5.2.7 on 2025-10-08 11:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(help_text='ISO 4217 currency code (e.g., USD, GBP, KES)', max_length=3, unique=True)),
                ('currency_name', models.CharField(help_text='Full currency name (e.g., US Dollar, British Pound)', max_length=100)),
                ('rate_to_ugx', models.DecimalField(decimal_places=4, help_text='Exchange rate: 1 [Currency] = X UGX', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('symbol', models.CharField(help_text='Currency symbol (e.g., $, £, €)', max_length=10)),
                ('decimal_places', models.IntegerField(default=2, help_text='Number of decimal places for this currency')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this currency is currently available for selection')),
                ('rate_source', models.CharField(choices=[('manual', 'Manual'), ('api', 'API')], default='manual', help_text='How this rate was set', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When the rate was last updated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'db_table': 'exchange_rate',
                'ordering': ['currency_code'],
            },
        ),
    ]
