# Generated by Django 5.2.7 on 2025-10-02 19:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '__first__'),
        ('preconfigured_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='Uganda', max_length=100)),
            ],
            options={
                'verbose_name': 'Shipping Address',
                'verbose_name_plural': 'Shipping Addresses',
                'db_table': 'shippingaddress',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('custom_name', models.CharField(blank=True, max_length=255, null=True)),
                ('base_product_name', models.CharField(max_length=255)),
                ('preconfigured_product', models.ForeignKey(db_column='preconfigured_product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='preconfigured_products.preconfiguredproduct')),
            ],
            options={
                'db_table': 'orderproduct',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=255)),
                ('option_name', models.CharField(max_length=255)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_payment_required', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_product', models.ForeignKey(db_column='order_product_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orderproduct')),
            ],
            options={
                'db_table': 'orderitem',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_required_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('fulfillment_status', models.CharField(choices=[('pending', 'Pending'), ('in_production', 'In Production'), ('ready_for_pickup', 'Ready for Pickup'), ('in_delivery', 'In Delivery'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('is_fulfillable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer')),
                ('shipping_address', models.ForeignKey(db_column='shipping_address_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.shippingaddress')),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.orders'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.CharField(choices=[('customer', 'Customer'), ('delivery_person', 'Delivery Person')], default='customer', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.orders')),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['-payment_date'],
            },
        ),
    ]
