# Generated by Django 5.2.7 on 2025-10-07 14:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shipping cost in UGX', max_digits=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Products subtotal before shipping', max_digits=10),
        ),
    ]
