# Generated by Django 5.2.7 on 2025-10-02 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        # Add payment tracking fields to Orders model
        migrations.AddField(
            model_name='orders',
            name='minimum_required_amount',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('partial', 'Partial'), ('completed', 'Completed')],
                default='pending',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='orders',
            name='is_fulfillable',
            field=models.BooleanField(default=False),
        ),

        # Add minimum_payment_required field to OrderItem model
        migrations.AddField(
            model_name='orderitem',
            name='minimum_payment_required',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
        ),

        # Create Payment model
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.CharField(
                    choices=[('customer', 'Customer'), ('delivery_person', 'Delivery Person')],
                    default='customer',
                    max_length=20
                )),
                ('transaction_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(
                    db_column='order_id',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='payments',
                    to='orders.orders'
                )),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['-payment_date'],
            },
        ),
    ]
