# Generated by Django 5.2.7 on 2025-10-08 11:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_shipping_cost_orders_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='base_currency_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price in base currency (UGX) for reporting', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='exchange_rate_snapshot',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Exchange rate at time of order (1 order_currency = X UGX)', max_digits=12),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_currency',
            field=models.CharField(default='UGX', help_text='Currency in which the order was placed (ISO 4217 code)', max_length=3),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shipping cost', max_digits=10),
        ),
    ]
