# Generated by Django 5.2.7 on 2025-10-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='fulfillment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_production', 'In Production'), ('ready_for_pickup', 'Ready for Pickup'), ('in_delivery', 'In Delivery'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
