# Generated by Django 5.2.7 on 2025-10-11 14:05

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_customer_preferred_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('context', models.JSONField(default=dict, help_text='Stores current page, cart state, configuration state, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Associated customer (null for anonymous users)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
            ],
            options={
                'db_table': 'ai_chat_session',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict, help_text='Product IDs, configuration suggestions, action types, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.aichatsession')),
            ],
            options={
                'db_table': 'ai_chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIEmbeddedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('product', 'Preconfigured Product'), ('part_option', 'Part Option'), ('category', 'Category'), ('compatibility_rule', 'Compatibility Rule'), ('faq', 'FAQ')], max_length=50)),
                ('document_id', models.IntegerField(help_text='ID of the source document')),
                ('content', models.TextField(help_text='Text content to be embedded')),
                ('metadata', models.JSONField(default=dict, help_text='Additional data like category_id, price, tags, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_embedded_document',
                'indexes': [models.Index(fields=['document_type', 'document_id'], name='ai_embedded_documen_0f8796_idx'), models.Index(fields=['document_type'], name='ai_embedded_documen_20d6ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_product_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, help_text='List of recommended product IDs', size=None)),
                ('context', models.JSONField(default=dict, help_text='User query and context at time of recommendation')),
                ('user_action', models.CharField(blank=True, help_text='Action taken: viewed, added_to_cart, ignored', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='ai_assistant.aichatsession')),
            ],
            options={
                'db_table': 'ai_recommendation',
                'ordering': ['-created_at'],
            },
        ),
    ]
