# Generated by Django 5.2.7 on 2025-10-04 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_name', models.CharField(choices=[('stripe', 'Stripe'), ('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money')], max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('environment', models.CharField(default='sandbox', max_length=20)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('additional_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_gateway_config',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('stripe', 'Stripe'), ('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('requires_action', 'Requires Action'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='orders.orders')),
                ('payment', models.OneToOneField(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='orders.payment')),
            ],
            options={
                'db_table': 'payment_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='payment_tra_order_i_c6a3d5_idx'), models.Index(fields=['gateway_transaction_id'], name='payment_tra_gateway_9fb8fa_idx'), models.Index(fields=['status'], name='payment_tra_status_373de7_idx')],
            },
        ),
    ]
